version: 2.1
orbs:
  node: circleci/node@4.7.0
commands:
  build_image:
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=1.0
          docker build -t iwonder/aspera-transporter:$TAG .

jobs:
  build:
    executor:
      name: node/default
      tag: "10.4"
    steps:
      - build_image
