version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
commands:
  build_image:
    parameters:
      environment:
        type: string
        default: test
      tag:
        type: string
        default: '1.0'
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          node --version
          docker --version
          docker ps -a
          echo <<parameters.environment>>
          echo <<parameters.tag>>
jobs:
  build:
    docker: 
      - image: cimg/node:14.17.5
    parameters:
      environment:
        type: string
        default: staging
      tag:
        type: string
        default: '1.0'
    steps:
      - build_image:
          environment: <<parameters.environment>>
          tag: <<parameters.tag>>
workflows:
  version: 2
  "build_test":
    jobs:
      - build:
          context: staging
          tag: '2.0'
          environment: $ENV
    
