version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
commands:
  build_image:
    parameters:
      enviroment:
        type: string
        default: test
    steps:
      - run: |
          node --version
          docker --version
          docker ps -a
jobs:
  build:
    docker: 
      - image: cimg/node:14.17.5
    steps:
      - build_image:
          enviroment: hiep
