version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
  node: circleci/node@4.7.0
  docker: circleci/docker@1.7.0
commands:
  build_image:
    parameters:
      environment:
        type: string
        default: test
      tag:
        type: string
        default: '1.0'
    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: false
      - aws-cli/install
      - docker/install-docker
      - docker/install-docker-credential-helper
      - run: cat ~/.docker/config.json
          
jobs:
  build:
    executor: node/default
    parameters:
      environment:
        type: string
        default: staging
      tag:
        type: string
        default: '1.0'
    steps:
      - build_image:
          environment: <<parameters.environment>>
          tag: <<parameters.tag>>
workflows:
  version: 2
  "build_test":
    jobs:
      - build:
          context: staging
          tag: '1.0'
          environment: $ENV
    
