version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
commands:
  build_image:
    parameters:
      environment:
        type: string
        default: test
      tag:
        type: string
        default: '1.0'
    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: false
      - aws-cli/install
      - run: |
          # sudo apt update
          # sudo apt install amazon-ecr-credential-helper
          # whereis amazon-ecr-credential-helper
          # export PATH=${PATH}:$(whereis amazon-ecr-credential-helper)
          docker config inspect config.json
jobs:
  build:
    machine: true
    parameters:
      environment:
        type: string
        default: staging
      tag:
        type: string
        default: '1.0'
    steps:
      - build_image:
          environment: <<parameters.environment>>
          tag: <<parameters.tag>>
workflows:
  version: 2
  "build_test":
    jobs:
      - build:
          context: staging
          tag: '1.0'
          environment: $ENV
    
