version: 2.1
orbs:
  node: circleci/node@4.7.0
commands:
  build_image:
    steps:
      - checkout
      - run: |
          TAG=1.0
          docker build -t iwonder/aspera-transporter:$TAG .
          docker images
jobs:
  build:
    machine: true
    steps:
      - build_image
