version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@1.3.1
  docker-installer: circleci/docker@1.6.0
commands:
  build_image:
    parameters:
      enviroment:
        type: string
        default: test
    steps:
      - docker-installer/install-docker
      - checkout
      - run: echo <<parameters.enviroment>>
      - run: | 
          docker images
          # TAG=1.0
          # docker build -t iwonder/aspera-transporter:$TAG .
          # docker images
  upload_ecr:
    steps:
      - run: | 
          docker ps
jobs:
  build:
    executor: node/default
    steps:
      - build_image:
          enviroment: hiep
      - upload_ecr
